server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001   #eureka服务端的实例名称
  client:  
    register-with-eureka: false     #false表示不向注册中心注册自己    
    fetch-registry: false   #false表示自己是注册中心，职责就是维护服务实例，并不需要去检索服务    
    service-url:    
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与eureka server交互的地址查询服务和注册都依赖这个地址
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/